default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tickets
  port: 5432
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: tickets

production:
  <<: *default
